name: Build and Deploy

on:
  push:
    branches:
      - master
    paths-ignore:   
      - README.md
      - LICENSE
# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout master
#       uses: actions/checkout@v1
#       with:
#         submodules: true

#     - name: Hugo Deploy GitHub Pages
#       uses: benmatselby/hugo-deploy-gh-pages@master
#       env:
#         HUGO_VERSION: 0.70.0
#         TARGET_REPO: zqfang/zqfang.github.io
#         TOKEN: ${{ secrets.TOKEN }}
#         HUGO_ARGS: '-t LoveIt'
#         CNAME: zqfang.github.io

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.71.1'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
          external_repository: zqfang/zqfang.github.io # <- 改成你自己的 user github page
          publish_dir: ./public # <- 指定編譯後的成品放置的資料夾
          publish_branch: master # <- 遠端 repo 的目標分支