name: Build and Deploy

on:
  push:
    branches:
      - source  # default branch

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: somebuild

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
          deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
          #external_repository: zqfang/zqfang.github.io # <- 改成你自己的 user github page
