name: Publish Site

on: 
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive
 
      - name: Remove example Site
        run: rm -rf themes/LoveIt/exampleSite

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.72.0"
          extended: true

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SSH_DEPLOY_KEY }}
          external_repository: zqfang/zqfang.github.io
          publish_dir: ./public
          #   keep_files: true
          #publish_branch: master
          #cname: zqfang.github.io



